repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

#-   repo: https://github.com/PyCQA/pylint
#    rev: v2.15.5
#    hooks:
#      - id: pylint
